app:
  name: "my-awesome-app"
  version: "1.2"  # Invalid: should be semver format like "1.2.3"
  environment: "staging"

database:
  host: "localhost"
  port: 5432
  name: "my_app_db"

features:
  feature_a: true