app:
  name: "my-awesome-app"
  version: "1.2.3"
  environment: "{{ env_name | default('development') }}"

database:
  host: "{{ db_host | default('localhost') }}"
  port: 5432
  name: "my_app_db"

features:
  feature_a: true
  feature_b: false