app:
  name: "my-awesome-app"
  version: "1.2"  # Invalid: should be semver format like "1.2.3"
  environment: "testing"  # Invalid: not in allowed enum values

database:
  host: "localhost"
  port: 70000  # Invalid: port out of range
  # Missing required field: name

features:
  feature_a: true