app:
  name: "my-awesome-app"
  version: "1.2.3-beta"  # Invalid for ProductionConfigModel in production env
  environment: "production"

database:
  host: "localhost"  # Invalid for ProductionConfigModel
  port: 5432
  name: "my_app_db"

features:
  feature_a: true
  feature_b: "not_boolean"  # Invalid: should be boolean