flowchart TD
    output["`output_file / stdout `"]
    environment_variable["
    --env KEY=VALUE
    ...
    [--env KEY=VALUE]"]

    config_file["--config FILENAME/GLOB
    config file(s) 
    (*.json, *.yml, *.toml)"]

    template_file["--template FILENAME
    Jinja Template file"]

    environment_variable --> injinja
    config_file --> injinja
    template_file --> injinja
    injinja --> output