---
title: Validating Output Against Known Expectations
---
flowchart TD
    output["`output_file / stdout `"]
    environment_variable["
    --env KEY=VALUE
    ...
    [--env KEY=VALUE]"]

    config_file["base config file 
    -c base.yml"]
    glob_expression["Glob Expression
    -c '**/*.yml'"]
    override_file["base config file 
    -c override.yml"]

    template_file["Jinja Template file"]
    validate["Validation File
    --validate expectations-override.yml"]
    diff["Generate diff of output 
    and validation file"]

    environment_variable --> injinja
    config_file --> injinja
    glob_expression --> injinja
    override_file --> injinja
    template_file --> injinja
    validate --> injinja
    injinja --> output
    injinja --> diff

    classDef focus fill:#9c9,stroke:#beb,stroke-width:2px,color:#fff
    classDef other fill:#888,stroke:#999,stroke-width:2px,color:#ccc
    
    class validate,diff,injinja focus
    class config_file,glob_expression,override_file,template_file,output,environment_variable other