# https://docs.astral.sh/uv/guides/package/
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/injinja

    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Build the package
        run: uv build --wheel

      - name: Publish to PyPI
        run: uv publish